name: Unix build



on:
  push:
  pull_request:

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: carlosperate/arm-none-eabi-gcc-action@v1.8.1
      with:
        release: 'latest' # 9-2020-q2 The arm-none-eabi-gcc release to use.

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Deps
      run: |
        sudo apt-get update && sudo apt-get install --assume-yes --allow-downgrades --allow-remove-essential --allow-change-held-packages build-essential pkg-config cmake ninja-build libffi-dev gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev doxygen ccache
        git submodule update --init -- lib/pycparser
        git submodule update --init --jobs 4 -- lib/micropython        
        git submodule update --init --jobs 4 -- lib/lvgl        
        git submodule update --init --jobs 4 -- lib/SDL
        cd lib/SDL
        git checkout release-2.30.2
        cd ../..

    - name: Cached Deps
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          lib/esp-idf
          ~/.espressif
        key: ${{ runner.os }}-v4-deps

    - name: Get Build Deps
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        git submodule update --init --jobs 4 -- lib/esp-idf
        cd lib/esp-idf
        git submodule update --init --jobs 4 -- components/bt/host/nimble/nimble components/esp_wifi components/esptool_py/esptool components/lwip/lwip components/mbedtls/mbedtls components/bt/controller/lib_esp32 components/bt/controller/lib_esp32c3_family
        cd ../..
        export "IDF_PATH=${GITHUB_WORKSPACE}/lib/esp-idf"
        ./lib/esp-idf/install.sh all

    - name: Setup ESP-IDF
      run: |
        export "IDF_PATH=${GITHUB_WORKSPACE}/lib/esp-idf"
        . ./lib/esp-idf/export.sh

    - name: Build ESP32 port
      run: python3 make.py esp32 BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=rgb_display INDEV=gt911 --ccache

    # - name: Build STM32 port
    #   run: python3 make.py stm32 submodules clean mpy_cross BOARD=STM32H7B3I_DK DISPLAY=rgb_display INDEV=gt911

    # - name: Build Raspberry Pi PICO port
    #   run: python3 make.py rp2 submodules clean mpy_cross BOARD=RPI_PICO DISPLAY=rgb_display INDEV=gt911

    - name: Get build datetime
      id: datetime
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYY_MM_DD HH_mm_ss_SSS"

    - name: Build Unix port
      run: python3 make.py unix DISPLAY=sdl_display INDEV=sdl_pointer

    - uses: actions/upload-artifact@v4
      with:
        name: lvgl_micropy_unix-${{ steps.datetime.outputs.month }}.${{ steps.datetime.outputs.day }}.${{ steps.datetime.outputs.year }}-${{ steps.datetime.outputs.hours }}_${{ steps.datetime.outputs.minutes }}_${{ steps.datetime.outputs.seconds }}
        path: build/lvgl_micropy_unix
        if-no-files-found: ignore
